# /* wallust template - colors-kitty */

foreground         #B2ABAA
background         #351511
cursor             #C78178

active_tab_foreground     #351511
active_tab_background     #B2ABAA
inactive_tab_foreground   #B2ABAA
inactive_tab_background   #351511

active_border_color   #B2ABAA
inactive_border_color #351511
bell_border_color     #4E2B27

color0      #382420
color1		#4E2B27
color2		#67312B
color3		#823A31
color4		#A14237
color5		#B9493B
color6		#C3523F
color7		#887F7D
color8		#5F5958
color9		#542E28
color10		#76362F
color11		#9A4036
color12		#C34C3E
color13		#DE4330
color14		#F75A40
color15		#887F7D
