# /* wallust template - colors-hyprland */ 

$background = rgb(351511)
$foreground = rgb(B2ABAA)
$color0 = rgb(382420)
$color1 = rgb(4E2B27)
$color2 = rgb(67312B)
$color3 = rgb(823A31)
$color4 = rgb(A14237)
$color5 = rgb(B9493B)
$color6 = rgb(C3523F)
$color7 = rgb(887F7D)
$color8 = rgb(5F5958)
$color9 = rgb(542E28)
$color10 = rgb(76362F)
$color11 = rgb(9A4036)
$color12 = rgb(C34C3E)
$color13 = rgb(DE4330)
$color14 = rgb(F75A40)
$color15 = rgb(887F7D)
